arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Rev30
    - Rev31
    - Rev32
    - Slider33
    - Rev34
    - Rev35
    - Rev36
  gains:
    Rev30:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev31:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev32:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Slider33:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev34:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev35:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev36:
      p: 100
      d: 1
      i: 1
      i_clamp: 1